name: Maven verify
#run-name: ${{ github.actor }} ran maven verify on GitHub Actions ğŸš€
#run-name: maven verify - ${{ github.actor }} at ${{ github.ref }} ğŸš€
on: [ push ]
jobs:
  Describe:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ Author ${{ github.actor }}"
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

  MavenVerify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
          cache: 'maven'
          check-latest: false

      - name: Run maven verify
        run: ${{ github.workspace }}/mvnw clean verify
      - run: echo "ğŸ This job's status is ${{ job.status }}."
